"""Schema changed

Revision ID: b04868f1ad1b
Revises: c35d4ad05b54
Create Date: 2026-02-17 19:02:08.554334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b04868f1ad1b'
down_revision: Union[str, Sequence[str], None] = 'c35d4ad05b54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_chats_user_id'), 'chats', ['user_id'], unique=False)
    op.create_index(op.f('ix_messages_chat_id'), 'messages', ['chat_id'], unique=False)
    op.create_index(op.f('ix_pdf_documents_chat_id'), 'pdf_documents', ['chat_id'], unique=False)
    op.alter_column('quiz_options', 'text',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_quiz_options_question_id'), 'quiz_options', ['question_id'], unique=False)
    op.alter_column('quiz_questions', 'question',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_quiz_questions_quiz_id'), 'quiz_questions', ['quiz_id'], unique=False)
    op.drop_column('quiz_questions', 'answer')
    op.create_index(op.f('ix_quizzes_chat_id'), 'quizzes', ['chat_id'], unique=False)
    op.drop_column('quizzes', 'completed_at')
    op.alter_column('summaries', 'content',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_summaries_chat_id'), 'summaries', ['chat_id'], unique=False)
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=False))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('users', 'hashed_password')
    op.drop_index(op.f('ix_summaries_chat_id'), table_name='summaries')
    op.alter_column('summaries', 'content',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('quizzes', sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_quizzes_chat_id'), table_name='quizzes')
    op.add_column('quiz_questions', sa.Column('answer', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_quiz_questions_quiz_id'), table_name='quiz_questions')
    op.alter_column('quiz_questions', 'question',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_quiz_options_question_id'), table_name='quiz_options')
    op.alter_column('quiz_options', 'text',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_pdf_documents_chat_id'), table_name='pdf_documents')
    op.drop_index(op.f('ix_messages_chat_id'), table_name='messages')
    op.drop_index(op.f('ix_chats_user_id'), table_name='chats')
    # ### end Alembic commands ###
